name = "Algoim"
uuid = "0eb9048c-21de-4c7a-bfac-056de1940b74"
authors = ["Eric Neiva <eric.miranda-neiva@college-de-france.fr>"]
version = "0.2.1"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
algoimWrapper_jll = "3c43aa7b-5398-51f3-8d75-8f051e6faa4d"

[compat]
CxxWrap = "0.16"
StaticArrays = "1.5"
algoimWrapper_jll = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
